sonar.projectKey=Elysium-Labs-EU_theia
sonar.organization=elysium-labs-eu

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
